version: '3.8'

services:
  frontend:
    image: heryfik/cilist-pipeline-fe:${GIT_COMMIT_SHORT}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://ec2-13-211-170-220.ap-southeast-2.compute.amazonaws.com:5000